server:
  port: 9000
spring:
  application:
    name: gotravels-gateway${unique-name:}-service
  profiles:
    active: aggregation
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}